### ISSUE TITLE
Consultation over the hardware information.

### ISSUE THREAD

**Issue by Starboy-at-earth** [GewelsJI/FSNet#1]
Dear Author:
       Could you please tell me how many GPUs do you use. to train the model? Thank you inadance!!!

**Comment by GewelsJI** [comment]
I use two Nvidia 2080 GPUs to train my model. You can also use a single card to complete it.

Best,
Ge-Peng.

**Comment by Starboy-at-earth** [comment]
@GewelsJI You definitely are the most adorable one against the increasingly computing force rising backdrop... Thank you for your in-time reply.

**Comment by GewelsJI** [comment]
I pretty much appreciate your positive feedback. In our framework, I do not think big data makes big changes. But one more important we should notice is that network architecture and training strategy.

Thank you again. Best.
