### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by xubangwu** [GewelsJI/FSNet#11]
Hello, this is a great work. But when I use weights provided in the link [Baidu Driver](https://pan.baidu.com/s/1GRUg-n1EEV_nku-2nG3QRw) (psw: 36lm) to test on the DAVIS16 dataset, the mean-J and mean-F are only 47.5 and 27.8, respectively. I want to know if the weights are the final weights?

**Comment by GewelsJI** [comment]
Hi, @xubangwu

Thank you for your attention.

NOTE: In the U-VOS task, all the prediction results are strictly binary. We only adopt the naive binarization algorithm (i.e., threshold=0.5) in our experiments.

Thus, please ensure the results generated are processed into binary form.

**Comment by xubangwu** [comment]
Thanks, I get it now.
