### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chengguanjun** [GewelsJI/FSNet#12]
您好，请问我在加载两个预训练模型的时候出现以下错误是什么原因呢？好像是update_predict这个函数出现了问题，如果能得到您的帮助我将感激不尽。
![ST3JN`KAP%8%(0Z~Y4$8FDJ](https://user-images.githubusercontent.com/64786229/178197823-ba489407-74ae-4199-aa8d-00e2df3eec8d.png)

**Comment by qhtang21** [comment]
您好，请问您解决了这个问题吗，我也出现了相同的报错

**Comment by chengguanjun** [comment]
我是按照报错代码位置的前面的代码修改了一下，你可以试一下
