### ISSUE TITLE
spatial branch和temporal branch的权重

### ISSUE THREAD

**Issue by xubangwu** [GewelsJI/FSNet#13]
你好，可以提供spatial branch和temporal branch预训练好的权重吗？我想微调一下。

**Comment by GewelsJI** [comment]
@xubangwu 👋你好，很感谢您对我们工作的关注！

由于个人工作单位多次更换原因，对应的预训练权重存储不慎丢失，很难去回溯到给您，望理解。

不过对应的训练细节在这里面展示出来：https://github.com/GewelsJI/FSNet#how-to-train-our-model-from-scratch

我这边几位学弟近期的几次复现结果来看，是可以对应上原文的，你资源充分的话可以自行重新训练一下。

祝好！

**Comment by xubangwu** [comment]
你好，请问这两个分支训练时batch size和epoch都是8和50吗？
