### ISSUE TITLE
finetune无法读取已训练完的光流权重和RGB权重

### ISSUE THREAD

**Issue by zp19990818** [GewelsJI/FSNet#16]
学长好，我用项目提供的数据集分别对rgb和光流进行训练，得到了两个分支的权重，然后在func.py修改了这两个权重的路径，但是在做finetune的时候，读取出来的权重不对，我看先前有同学提问，但是是在双卡上训练的。我是单卡3090训练，所以可能不是学长说的model.moudle的问题，可以麻烦学长看一下我的bug吗？是训练权重不对还是？
![image](https://user-images.githubusercontent.com/53686038/217785844-00cefebd-c861-4c1f-b967-90afeaa1c129.png)
![image](https://user-images.githubusercontent.com/53686038/217786146-6024ac81-5fbb-4715-b28d-fd209c59c77d.png)

**Comment by GewelsJI** [comment]
你好，你把keys中的module前缀去掉即可加载在单卡上了。

**Comment by zp19990818** [comment]
感谢学长的建议！我在func.py最后面修改去掉了module，现在运行起来了，这应该是读取到了预训练的单分支权重了吧，我怕啥都没读取到就开始finetune了，因为我看CSDN有人这样干，这也不报错但是也没加载到预训练的权重。我的截图如下：
![image](https://user-images.githubusercontent.com/53686038/217802565-b203cd53-a3ef-4342-a8b2-2b887ee96967.png)

**Comment by zp19990818** [comment]
学长，我再补一张图
![image](https://user-images.githubusercontent.com/53686038/217803712-f6443f64-ac2b-4892-acd9-dbe16883d9aa.png)

**Comment by GewelsJI** [comment]
我初步看是没问题的，具体你可以把加载前后的key-value数值对，检查并对比一下

**Comment by zp19990818** [comment]
> 我初步看是没问题的，具体你可以把加载前后的key-value数值对，检查并对比一下

明白！谢谢学长的帮助🌹
