### ISSUE TITLE
evaluation related----whether there are other methods that run in python environment to evaluate the weights or not

### ISSUE THREAD

**Issue by xiangwentao666** [GewelsJI/FSNet#17]
If there are other methods that **run in python environment** to evaluate the weights, please tell me as soon as possible, thank you very much!!!!!!!!!!!

**Comment by GewelsJI** [comment]
hi, @xiangwentao666, I didn't get you. please give more details about "evaluate the weights"

**Comment by xiangwentao666** [comment]
Thank you so much for your timely reply! 

I've finished all the three training stages, and also finished the inference process on all datasets. What I want to do right now is to evaluate the masks generated during the inference process, which could be done by running the scripts in the folder named "eval". However, the files in the "eval" folder are in the format of Matlab(each ends with ".m") and software "Matlab" might need to be installed(I'm actually not familiar with Matlab). So, I would like to ask you whether there exist other ways to accomplish the same purpose as the ".m" scripts can do.

**Comment by xiangwentao666** [comment]
> hi, @xiangwentao666, I didn't get you. please give more details about "evaluate the weights"

Thank you so much for your timely reply!

I've finished all the three training stages, and also finished the inference process on all datasets. What I want to do right now is to evaluate the masks generated during the inference process, which could be done by running the scripts in the folder named "eval". However, the files in the "eval" folder are in the format of Matlab(each ends with ".m") and software "Matlab" might need to be installed(I'm actually not familiar with Matlab). So, I would like to ask you whether there exist other ways to accomplish the same purpose as the ".m" scripts can do.

**Comment by GewelsJI** [comment]
Hi, @xiangwentao666 

Thanks for your reaching out. There are two alternatives: 
- as for UVOS task, you can use evaluation toolbox of DAVIS: https://github.com/fperazzi/davis 
- as for VSOD task, you can use evaluation toolbox of VPS with small modifications: https://github.com/GewelsJI/VPS/tree/main/eval

Hope these resource helps you a lot.

Best.

**Comment by xiangwentao666** [comment]
> Hi, @xiangwentao666
> 
> Thanks for your reaching out. There are two alternatives:
> 
> * as for UVOS task, you can use evaluation toolbox of DAVIS: https://github.com/fperazzi/davis
> * as for VSOD task, you can use evaluation toolbox of VPS with small modifications: https://github.com/GewelsJI/VPS/tree/main/eval
> 
> Hope these resource helps you a lot.
> 
> Best.


Wow, detailed and helpful!
The solutions you mentioned will be considered, and actually I'm new to this area and new to research, so there could be many mistakes or much trouble.
Thank you for your reply and your patience! 
AGAIN, thanks a million!!!!!!!!!!

**Comment by GewelsJI** [comment]
Welcome. This issue has been solved.
