### ISSUE TITLE
Matlab Code Used for Evaluation Related Questions, parallel computing, gpu

### ISSUE THREAD

**Issue by xiangwentao666** [GewelsJI/FSNet#18]
Hi, the Matlab code is easy to use and it has been modified very soon to generate the evaluation result. However, the efficiency is still low because of using CPU only. So, how can I speed up it like using the GPU to process the images?

**Comment by GewelsJI** [comment]
you can use parfor mode in Matlab

**Comment by xiangwentao666** [comment]
I will have a try, thank you a lot!
