### ISSUE TITLE
Evaluation Related; Meanings of Metrics in the Output Text File Related;

### ISSUE THREAD

**Issue by xiangwentao666** [GewelsJI/FSNet#19]
`seq_Smeasure:0.135;seq_wFmeasure:0.095;seq_adpFmeasure:0.041;seq_maxF:0.185;seq_meanF:0.121;seq_adpEmeasure:0.249;seq_maxE:0.627;seq_meanE:0.202;seq_MAE:0.819`
Above is one of the lines in the output file, and some pairs have been found in the paper:
`Smeasure  ——  4.2.2 5. structure measure`
`wFmeasure  —— ` 
`adpFmeasure  ——  `
`maxF  ——  maximum F-measure`
`meanF  ——  `
`adpEmeasure  ——  `
`maxE  ——  4.2.2 4. Maximum Enhanced-Alignment Measure`
`meanE  ——  `
`seq_MAE  ——  4.2.2 mae`

However, the meanings of the variables not found are still not clear, could you please help me about this? Thank you sincerely!

**Comment by GewelsJI** [comment]
Kindly suggest you read original paper carefully. Please see Section 4.2 in https://link.springer.com/article/10.1007/s41095-021-0262-4
