### ISSUE TITLE
the update_predict function  defined in func.py?

### ISSUE THREAD

**Issue by xiaobai65** [GewelsJI/FSNet#5]
您好，您的update_predict 代码是不是有些问题？ 您的代码似乎是用 pretrain_rgb 权重中的 resnet.conv1 ; resnet.bn1的权重去替换 模型中  resnet.conv1_rgb ; resnet.bn1_rgb 的权重了

**Comment by GewelsJI** [comment]
@xiaobai65 
你好，这一部分涉及到加载rgb部分（即：video frames）作为appearance branch的预训练权重，而不是直接加载ImageNet的预训练权重
