### ISSUE TITLE
指标算不出来

### ISSUE THREAD

**Issue by PengPanda** [GewelsJI/FSNet#6]
用文件中的evaluation算不出来maxE 和 maxF, 都是0.000，请问是为什么？

**Comment by GewelsJI** [comment]
你好，

可以取消注释一下这几行：99-106（https://github.com/GewelsJI/FSNet/blob/e9fd0e2c6f7e36b7c004ce05e321ec417d4d9632/eval/main_VSOD.m#L99）但是会比较耗时，所以我注释掉了
