### ISSUE TITLE
中文版论文

### ISSUE THREAD

**Issue by zhangh0920** [GewelsJI/FSNet#7]
论文中文版本链接失效了，可以重新提供一下吗

**Comment by GewelsJI** [comment]
Hi, @zhangh0920 

Many thanks for your attention to our work. I uploaded the Chinese translation version of our paper at [here](https://github.com/GewelsJI/FSNet/blob/main/assets/ICCV2021_VSOD_FSNet_Chinese.pdf). 

Best,
Ge-Peng.

**Comment by zhangh0920** [comment]
Thanks a lot!
