### ISSUE TITLE
您好, 打扰了有几个问题想请教下您

### ISSUE THREAD

**Issue by aflyingnoob** [GewelsJI/FSNet#8]
1. 请问下您只用了DAVIS和FBMS训练, 没用DAVSOD-train吗?
2. FBMS的标签只有部分有, 您是只用对应的那部分帧来训练吗?
3. 我用您的模型在DAVSOD/DAVIS试着跑了下, 在Eeasy35上测试效果不错, 但是在小数据集DAVIS/FBMS上效果一般, 甚至觉得小数据集直接当做图片来做效果还更好 : ) 您有遇到过这方面的问题或者您有啥看法?谢谢.

**Comment by GewelsJI** [comment]
你好，感谢你的关注！

1、是的，我们并没有使用DAVSOD
2、是的，仅使用了标注过的部分帧
3、DAVIS上面的性能应该还不错，我们的模型取得了当时的SOTA效果。FBMS数据集比较老了，我们没有针对其进行测评。效果不好可能是因为数据集本身原因（猜测因为分辨率低？光流质量不高？运动模式不明显？）可能都会有原因。

**Comment by TianXuXiang** [comment]
> 

你好，学长，我想问一下，在VOS任务上：原论文没有给出FBMS的结果，但是我测出来的FBMS结果还不错，比现在的一些模型都差不多，学长是因为一些原因没有放上去吗？还是因为其他的吗

**Comment by GewelsJI** [comment]
已经提供了对比结果，请参考原文：
<img width="1099" alt="image" src="https://github.com/GewelsJI/FSNet/assets/38354957/dccca738-e4a9-4118-a555-4281d93f889a">

**Comment by aflyingnoob** [comment]
别卷了别卷了....周末一点钟还在卷QAQ

**Comment by TianXuXiang** [comment]
> 已经提供了对比结果，请参考原文： <img alt="image" width="1099" src="https://user-images.githubusercontent.com/38354957/250150251-dccca738-e4a9-4118-a555-4281d93f889a.png">

但是这个是V-SOD任务的数据呀，视频分割的还是没找到，(*^_^*)

**Comment by GewelsJI** [comment]
可以自行测试一下

**Comment by TianXuXiang** [comment]
> 可以自行测试一下

嗯嗯，那就是原文没给这个结果喽？，那我自己测试一下吧
谢谢学长

**Comment by GewelsJI** [comment]
不客气，祝好
