### ISSUE TITLE
Inference on custom dataset

### ISSUE THREAD

**Issue by Amrou7** [GewelsJI/FSNet#9]
Thank you for sharing this work.
I want to know how to do inference on our personalized dataset, without any ground truth masks and without OF_FlowNet2 images. We only have frames on which we want to detect moving persons. Thank you in advance

**Comment by GewelsJI** [comment]
Hi, @Amrou7 

Thank you for your attention to our work.

You first synthesize the optical flow map via FlowNet2.0 generator. The ground-truth masks are not necessary if you do not need to evaluate the performance.

Best,
Ge-Peng.
